source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

    workspace 'ICSerializer'
    project 'ICSerializer'
	
    target 'ICSerializerDemo' do
       pod 'ICSerializer', :path => '../'
    end

    target 'ICSerializer_Tests' do
       pod 'ICSerializer', :path => '../'
    end
